### ISSUE TITLE
New versions without change??

### ISSUE THREAD

**Issue by theCuriousOne** [ben-eb/gulp-csso#27]
Is there any reason to do upgrade of a version number without having actual changes? 
It is annoying to have to check for changes every time the version changes and finding out there are no changes at all.

**Comment by lahmatiy** [comment]
Well, it has huge changes under the hood. 
Recently [CSSO is released](https://github.com/css/csso/releases/tag/v3.0.0) and changed its major version to 3.0, because of using a brand new CSS parser, I personally [worked on for last months](https://github.com/csstree/csstree/releases).
Yep, generally, there are no changes for end-users in API. I believe you will not notice any changes using CSSO new version or related plugins except in a positive way (better parsing and performance). But it's a significant change in a code base. That's why major version was changed, to indicate that something may go wrong.

**Comment by theCuriousOne** [comment]
Ok, thanks for the fast reply. But please if you can add at least a comment that on the gulp-csso someting like "Updating dependencies"... or something similar. Anyway thanks for your good work.

**Comment by lahmatiy** [comment]
Do you mean releases page or something else?
You can find notes about changes in [CHANGELOG.md](https://github.com/ben-eb/gulp-csso/blob/master/CHANGELOG.md).

**Comment by theCuriousOne** [comment]
Yes. I saw that, but got confused by reading it as GULP-CSSO instead of just CSSO. A link to the changes reqarding CSSO would be much better according to me. But it;s my bad. Sorry :)

**Comment by lahmatiy** [comment]
It's a good idea, I've added links to CSSO release notes in [CHANGELOG.md](https://github.com/ben-eb/gulp-csso/blob/master/CHANGELOG.md)
