### ISSUE TITLE
Error: CSS parse error dress-code.min.css: RightParenthesis is expected

### ISSUE THREAD

**Issue by rbarilani** [ben-eb/gulp-csso#29]
After updating to gulp-csso@3.0.0, I have a new error.

npm --version 4.1.2
node --version 7.7.3

```
Error: CSS parse error dress-code.min.css: RightParenthesis is expected
 2903 |}
 2904 |
 2905 |@media (min-width: 0 37.4em) {
----------------------------^
 2906 |  .dc-table--responsive {
 2907 |    display: block;
```

from [dress-code](https://github.com/zalando/dress-code) project

**Comment by lahmatiy** [comment]
The CSS parser in CSSO 3.0 is more strcit in parsing for some things like media features. Your CSS looks incorrect, since a media feature value can one of number, dimension, identifier or ratio. But not a list of values.
Does it work in any browser?
I've tested in few browsers: Chrome and Firefox ignore that media, and Edge always applyes (looks like it ignores second value - `37.4em`). Is it a hack maybe?

**Comment by rbarilani** [comment]
@lahmatiy thx for the quick extensive answer. It looks like that we miss that point when we removed "breakpoint" library magic.... @sambhav-gore

**Comment by rbarilani** [comment]
close this. The problem was on our side. @lahmatiy  Thanks again.

**Comment by lahmatiy** [comment]
@rbarilani Take a look at [csstree](https://github.com/csstree/csstree) (CSSO uses it under the hood), it has a validation feature and several ready to use plugins (and even [online validator](https://csstree.github.io/docs/validator.html)) to test CSS compliance to spec and browser implementations. It may help you to find more problems in your CSS.
