### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by caibirdme** [ben-eb/gulp-csso#9]
Every time I `gulp build`,it will report this error information, while I can `gulp serve` which runs well.
![2015-06-23 5 52 24](https://cloud.githubusercontent.com/assets/8054803/8303472/c55c3302-19d0-11e5-8139-fdf99183af40.png)
I don't know if it should be blamed to the edition of node or gulp,my node is `0.10.35`
![2015-06-23 5 56 26](https://cloud.githubusercontent.com/assets/8054803/8303556/36884782-19d1-11e5-8382-42cde6c30f24.png)

**Comment by ben-eb** [comment]
Looks like a csso error to me. I would consider switching your compression tool to either clean-css (https://github.com/jonathanepollack/gulp-minify-css) or cssnano (https://github.com/ben-eb/gulp-cssnano) which I wrote and has a modern codebase based on PostCSS.

csso currently has no maintainer and many open issues. It's not really worth opening an issue upstream because of this, but it is not an error with the gulp plugin. Try one of the alternatives I suggested instead. :smile:
